# Generated by Django 3.1.7 on 2021-06-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20210623_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='qty',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
